# Generated by Django 6.0.3 on 2026-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload a medical certificate or proof (Optional)', null=True, upload_to='leaves/attachments/'),
        ),
    ]
