# Generated by Django 6.0.3 on 2026-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_status_leaverequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='user',
        ),
    ]
