# Generated by Django 6.0.3 on 2026-04-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_remove_leaverequest_status_remove_leaverequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='employee_name',
            new_name='student_name',
        ),
    ]
