# Generated by Django 6.0.3 on 2026-04-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
